on0:
  push:
    tags:
      - 'release-*.*.*'
      - 'testing-*.*.*'
  workflow_dispatch:

jobs0:
  build:
    name: build and push docker image
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Git Tag
        run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: montekristall/admin-panel:${{ env.GIT_TAG }}
